-- Create vendors table
CREATE TABLE vendors (
    vendor_id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legal_name           VARCHAR2(255) NOT NULL,
    trade_name           VARCHAR2(255),
    tax_id               VARCHAR2(100),
    registration_number  VARCHAR2(100),
    business_type        VARCHAR2(100),
    country_of_incorp    VARCHAR2(100),
    date_established     DATE,
    created_at           TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create address_types table
CREATE TABLE address_types (
    type_code   VARCHAR2(50) PRIMARY KEY,
    label       VARCHAR2(100)
);

-- Insert sample address types
INSERT INTO address_types (type_code, label) VALUES
('order_to', 'Order To');

INSERT INTO address_types (type_code, label) VALUES
('ship_from', 'Ship From');

INSERT INTO address_types (type_code, label) VALUES
('invoice_from', 'Invoice From');

INSERT INTO address_types (type_code, label) VALUES
('remit_to', 'Remit To');

INSERT INTO address_types (type_code, label) VALUES
('return_to', 'Return To');

-- Create vendor_addresses table
CREATE TABLE vendor_addresses (
    address_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor_id       NUMBER NOT NULL,
    type_code       VARCHAR2(50) NOT NULL,
    contact_name    VARCHAR2(255),
    phone           VARCHAR2(50),
    email           VARCHAR2(255),
    address_line1   VARCHAR2(255) NOT NULL,
    address_line2   VARCHAR2(255),
    city            VARCHAR2(100),
    state           VARCHAR2(100),
    postal_code     VARCHAR2(20),
    country         VARCHAR2(100),
    is_default      NUMBER(1) DEFAULT 0,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_vendor_addresses_vendor_id FOREIGN KEY (vendor_id) REFERENCES vendors(vendor_id) ON DELETE CASCADE,
    CONSTRAINT fk_vendor_addresses_type_code FOREIGN KEY (type_code) REFERENCES address_types(type_code)
);

-- Create vendor_address_contacts table
CREATE TABLE vendor_address_contacts (
    contact_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address_id      NUMBER NOT NULL,
    contact_name    VARCHAR2(255) NOT NULL,
    role            VARCHAR2(100),
    email           VARCHAR2(255),
    phone           VARCHAR2(50),
    is_primary      NUMBER(1) DEFAULT 0,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_vendor_address_contacts_address_id FOREIGN KEY (address_id) REFERENCES vendor_addresses(address_id) ON DELETE CASCADE
);

-- Create address_chain table
CREATE TABLE address_chain (
    chain_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor_id       NUMBER NOT NULL,
    chain_label     VARCHAR2(255),
    order_to_id     NUMBER,
    ship_from_id    NUMBER,
    invoice_from_id NUMBER,
    remit_to_id     NUMBER,
    return_to_id    NUMBER,
    is_active       NUMBER(1) DEFAULT 1,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_address_chain_vendor_id FOREIGN KEY (vendor_id) REFERENCES vendors(vendor_id) ON DELETE CASCADE,
    CONSTRAINT fk_address_chain_order_to_id FOREIGN KEY (order_to_id) REFERENCES vendor_addresses(address_id),
    CONSTRAINT fk_address_chain_ship_from_id FOREIGN KEY (ship_from_id) REFERENCES vendor_addresses(address_id),
    CONSTRAINT fk_address_chain_invoice_from_id FOREIGN KEY (invoice_from_id) REFERENCES vendor_addresses(address_id),
    CONSTRAINT fk_address_chain_remit_to_id FOREIGN KEY (remit_to_id) REFERENCES vendor_addresses(address_id),
    CONSTRAINT fk_address_chain_return_to_id FOREIGN KEY (return_to_id) REFERENCES vendor_addresses(address_id)
); 